GoPlus - TokensList.org-Style Attestation List
ethereum-optimism/ecosystem-contributions pull request #187
Opened 2024-05-13 02:02 UTC by Elpeze

Hi from Goplus team,
As GoPlus, we offer security solutions for users in the crypto market. Therefore, since we work on the security of tokens, we are very experienced in the field of token classification.

We are ready to use our experience for [TokensList.org-Style Attestation List](https://contribute.optimism.io/issue/token-list-style-attestation-list).

The TokensList allows users to publish and discover lists of tokens maintained by teams and projects. These lists of tokens make it possible for teams to signal the legitimacy of certain tokens and help users filter out spam. We need this same kind of infra for the Attestation Station.

Possible Features
-An instance of an attestation list following a standard JSON schema and can -be hosted publicly on ENS, IPFS, or HTTPS.
-Context on what attestation lists are
-Directions on how to validate that a schemas follow the proposed standard
-Directions on how to author a attestation list
     List data
            List URL
            List Name
            List version
            Link to the official homepage of the list manager
    Attestation data
            Attestation name
            Attestation author
            Attestation key
            Attestation value
            Attestation image
            Attestation description
-Directions on how to deploy an attestation list
-Examples of what a attestation list looks like

2024-05-28 16:05 UTC, Nicca42 requested changes

2024-05-28 16:05 UTC, Nicca42 commented on contributions/token-list-style-attestation-list.md
> +authors: [@0xelpeze (Twitter) @ GoPlusSecurity" ,  "@theyavuzaslan (Twitter) @ GoPlusSecurity" ]
You are not the author of this idea, please remove this change.

2024-08-07 16:44 UTC, opjulian approved these changes

2024-08-07 16:45 UTC, opjulian commented
Hi, 

Branch has conflicts that must be resolved -- please resolve in order to be merged! 

Thanks!

2024-08-07 16:54 UTC, Elpeze commented
I will fix it as soon as possible. Thanks for letting me know

On Wed, Aug 7, 2024 at 19:45 opjulian ***@***.***> wrote:

> Hi,
>
> Branch has conflicts that must be resolved -- please resolve in order to
> be merged!
>
> Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-optimism/ecosystem-contributions/pull/187#issuecomment-2273891810>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR255WKEBFEWU6LUPBXYBN3ZQJFMDAVCNFSM6AAAAABHTKAGCOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZTHA4TCOBRGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-08-08 12:47 UTC, closed without merging